# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir Flask mysql-connector-python flask-cors

# Expose the port Flask runs on
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=main.py

# Command to run the Flask app
CMD ["flask", "run", "--host=0.0.0.0"]
